apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    # Same selector as for the ReplicaSet in order
    # to catch all pods
    app: random-generator
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  # Type ClusterIP for exposing the service only within the cluster
  type: ClusterIP
