apiVersion: v1
kind: Pod
metadata:
  name: non-root-with-uid
spec:
  securityContext:
    # If the container image is created for running on UID 0, you have to
    # set a non-0 UID so that runAsNonRoot will work
    runAsUser: 10000
    # Specify that all containers of this Pod are running as non-root
    runAsNonRoot: true
  containers:
  - name: random
    image: k8spatterns/random-generator:1.0
    # You could also put runAsNonRoot into container's securityContext 
    # securityContext:
    #   runAsNonRoot: true
