apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
spec:
  securityContext:
    # Specify that all containers of this Pod are running as non-root
    runAsNonRoot: true
  containers:
  - name: random
    image: k8spatterns/random-generator:1.0
    # You could also put runAsNonRoot into container's securityContext 
    # securityContext:
    #   runAsNonRoot: true
