apiVersion: v1
kind: Pod
metadata:
  name: read-only-fs-pod
spec:
  containers:
  - name: random
    image: k8spatterns/random:1.0
    securityContext:
      # Set the container's root filesystem as read-only
      readOnlyRootFilesystem: true  
