apiVersion: v1
kind: Pod
metadata:
  name: restricted-warning
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: random
    image: k8spatterns/random-generator:1.0
    securityContext:
      capabilities:
        drop: [ 'ALL' ]
        add: ['NET_BIND_SERVICE']
