apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  containers:
  - name: app
    image: k8spatterns/random-generator:1.0    
    securityContext:
      # Privileged is now allowed for a baseline security profile
      privileged: true
