apiVersion: v1
kind: Pod
metadata:
  name: read-only-fs-tmp-mount
spec:
  containers:
  - name: random
    image: k8spatterns/random-generator:1.0
    securityContext:
      # Set the container's root filesystem as read-only
      readOnlyRootFilesystem: true
    volumeMounts:
      # Mount an emptyDir to `/tmp` to allow Spring Boot to startup
      - name: tmp-volume
        mountPath: /tmp
  volumes:
  - name: tmp-volume
    emptyDir: {}
