name: Update Website

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        path: workdir/k8spatterns.io

    - name: Fetch branch gh-pages
      run: git fetch origin gh-pages
    
    - name: Install Hugo
      run: |
        curl -sSL "https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz" | tar -xz -C . hugo
        sudo mv hugo /usr/local/bin/
      working-directory: workdir
    
    - name: Generate site
      run: ./gen_site.sh
      working-directory: workdir/k8spatterns.io

